// ─── CURATED MODEL LIBRARY ───────────────────────────────────────────────────
// Every URL hand-picked for clothing visibility: full/upper/lower body, neutral pose.
// Unsplash photo IDs verified to show body / clothing clearly.

export const FEMALE_MODELS = [
  // ── FULL BODY ────────────────────────────────────────────────────────────
  {
    id: 'f-slim-full-casual',
    name: 'Emma',
    gender: 'female',
    body_type: 'Slim',
    style: 'Casual',
    age_group: 'Young Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1610173827021-4d2dc9c6b252?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'f-regular-full-casual',
    name: 'Sofia',
    gender: 'female',
    body_type: 'Regular',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'f-regular-full-fashion',
    name: 'Aisha',
    gender: 'female',
    body_type: 'Regular',
    style: 'Fashion',
    age_group: 'Young Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'f-curvy-full-casual',
    name: 'Keisha',
    gender: 'female',
    body_type: 'Curvy',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'f-plus-full-casual',
    name: 'Nia',
    gender: 'female',
    body_type: 'Plus Size',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1588117305388-c2631a279f82?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'f-athletic-full',
    name: 'Zara',
    gender: 'female',
    body_type: 'Athletic',
    style: 'Athletic',
    age_group: 'Young Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'f-mature-full-casual',
    name: 'Diane',
    gender: 'female',
    body_type: 'Regular',
    style: 'Mature',
    age_group: 'Mature',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=600&fit=crop&crop=center',
  },
  // ── UPPER BODY ───────────────────────────────────────────────────────────
  {
    id: 'f-slim-upper-casual',
    name: 'Maya',
    gender: 'female',
    body_type: 'Slim',
    style: 'Casual',
    age_group: 'Young Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=400&h=550&fit=crop&crop=top',
  },
  {
    id: 'f-regular-upper-street',
    name: 'Jordan',
    gender: 'female',
    body_type: 'Regular',
    style: 'Streetwear',
    age_group: 'Young Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=400&h=550&fit=crop&crop=top',
  },
  {
    id: 'f-plus-upper-casual',
    name: 'Rosa',
    gender: 'female',
    body_type: 'Plus Size',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=400&h=550&fit=crop&crop=top',
  },
  {
    id: 'f-athletic-upper',
    name: 'Dana',
    gender: 'female',
    body_type: 'Athletic',
    style: 'Athletic',
    age_group: 'Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1535743686920-55e4145369b9?w=400&h=550&fit=crop&crop=top',
  },
  // ── LOWER BODY ───────────────────────────────────────────────────────────
  {
    id: 'f-regular-lower-casual',
    name: 'Nadia',
    gender: 'female',
    body_type: 'Regular',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Lower Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?w=400&h=550&fit=crop&crop=bottom',
  },
  {
    id: 'f-slim-lower-fashion',
    name: 'Mia',
    gender: 'female',
    body_type: 'Slim',
    style: 'Fashion',
    age_group: 'Young Adult',
    view_type: 'Lower Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=550&fit=crop&crop=bottom',
  },
  {
    id: 'f-athletic-lower',
    name: 'Tara',
    gender: 'female',
    body_type: 'Athletic',
    style: 'Athletic',
    age_group: 'Young Adult',
    view_type: 'Lower Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=550&fit=crop&crop=bottom',
  },
];

export const MALE_MODELS = [
  // ── FULL BODY ────────────────────────────────────────────────────────────
  {
    id: 'm-slim-full-casual',
    name: 'Liam',
    gender: 'male',
    body_type: 'Slim',
    style: 'Casual',
    age_group: 'Young Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'm-regular-full-casual',
    name: 'Andre',
    gender: 'male',
    body_type: 'Regular',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'm-regular-full-street',
    name: 'Darius',
    gender: 'male',
    body_type: 'Regular',
    style: 'Streetwear',
    age_group: 'Young Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'm-athletic-full',
    name: 'Marcus',
    gender: 'male',
    body_type: 'Athletic',
    style: 'Athletic',
    age_group: 'Young Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'm-plus-full-casual',
    name: 'Omar',
    gender: 'male',
    body_type: 'Plus Size',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1604072366595-e75dc92d6bdc?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'm-mature-full-casual',
    name: 'Devon',
    gender: 'male',
    body_type: 'Regular',
    style: 'Mature',
    age_group: 'Mature',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop&crop=center',
  },
  {
    id: 'm-slim-full-fashion',
    name: 'James',
    gender: 'male',
    body_type: 'Slim',
    style: 'Fashion',
    age_group: 'Adult',
    view_type: 'Full Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop&crop=center',
  },
  // ── UPPER BODY ───────────────────────────────────────────────────────────
  {
    id: 'm-slim-upper-casual',
    name: 'Noah',
    gender: 'male',
    body_type: 'Slim',
    style: 'Casual',
    age_group: 'Young Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=550&fit=crop&crop=top',
  },
  {
    id: 'm-regular-upper-street',
    name: 'Jordan',
    gender: 'male',
    body_type: 'Regular',
    style: 'Streetwear',
    age_group: 'Young Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=400&h=550&fit=crop&crop=top',
  },
  {
    id: 'm-athletic-upper',
    name: 'Tyler',
    gender: 'male',
    body_type: 'Athletic',
    style: 'Athletic',
    age_group: 'Young Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=400&h=550&fit=crop&crop=top',
  },
  {
    id: 'm-plus-upper-casual',
    name: 'Ben',
    gender: 'male',
    body_type: 'Plus Size',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Upper Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=400&h=550&fit=crop&crop=top',
  },
  // ── LOWER BODY ───────────────────────────────────────────────────────────
  {
    id: 'm-slim-lower-casual',
    name: 'Ethan',
    gender: 'male',
    body_type: 'Slim',
    style: 'Casual',
    age_group: 'Young Adult',
    view_type: 'Lower Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=550&fit=crop&crop=bottom',
  },
  {
    id: 'm-regular-lower-casual',
    name: 'Caleb',
    gender: 'male',
    body_type: 'Regular',
    style: 'Casual',
    age_group: 'Adult',
    view_type: 'Lower Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=400&h=550&fit=crop&crop=bottom',
  },
  {
    id: 'm-athletic-lower',
    name: 'Miles',
    gender: 'male',
    body_type: 'Athletic',
    style: 'Athletic',
    age_group: 'Young Adult',
    view_type: 'Lower Body',
    thumbnail_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=550&fit=crop&crop=bottom',
  },
];

// Smart garment → model suggestion
export function getSuggestedModelId(garmentType, gender = 'female') {
  const map = {
    hoodie:     gender === 'male' ? 'm-regular-upper-street' : 'f-regular-upper-street',
    tshirt:     gender === 'male' ? 'm-slim-upper-casual'    : 'f-slim-upper-casual',
    jacket:     gender === 'male' ? 'm-regular-full-casual'  : 'f-regular-full-casual',
    dress:      'f-regular-full-fashion',
    pants:      gender === 'male' ? 'm-regular-lower-casual' : 'f-regular-lower-casual',
    activewear: gender === 'male' ? 'm-athletic-lower'       : 'f-athletic-lower',
  };
  return map[garmentType] || (gender === 'male' ? 'm-regular-full-casual' : 'f-regular-full-casual');
}